build-linux:
  docker:
    - image: cimg/rust:1.76
  steps:
    - checkout
    - node/install:
        node-version: "20"
    - run:
        name: Instalar dependencias de Tauri (Ubuntu 22.04)
        command: |
          apt-get update && apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
          npm install -g yarn
    - run:
        name: Compilar para Linux
        command: |
          cd src-tauri
          yarn install
          yarn tauri build --release --target x86_64-unknown-linux-gnu
    - run:
        name: Firmar binarios
        command: |
          cd src-tauri
          npm install -g @tauri-apps/cli  # Instalar Tauri CLI globalmente
          echo "$TAURI_PRIVATE_KEY" > private.key  # Crear archivo con la clave privada
          tauri signer sign -k private.key target/x86_64-unknown-linux-gnu/release/bundle/app.AppImage  # Ajusta según el binario generado
          cat target/x86_64-unknown-linux-gnu/release/bundle/app.AppImage.sig > signature.txt  # Guardar la firma
    - store_artifacts:
        path: src-tauri/target/x86_64-unknown-linux-gnu/release/bundle
        destination: linux-binaries
    - run:
        name: Subir a GitHub Releases
        command: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt update && apt install gh -y
          echo "$GITHUB_TOKEN" | gh auth login --with-token
          VERSION="v$(date +%Y%m%d%H%M)"
          SIGNATURE=$(cat src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/app.AppImage.sig)
          gh release create "$VERSION" src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/**/* --title "Release $VERSION" --notes "Firma: $SIGNATURE"
        environment:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
