name: "Create Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
      app_version:
        description: "App version from tauri.conf.json"
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: dominara-team/dominara
          token: ${{ secrets.RELEASES_TOKEN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        run: |
          git tag "v${{ inputs.version }}"
          git push origin "v${{ inputs.version }}"
          gh release create "v${{ inputs.version }}" \
            --title "Dominara v${{ inputs.app_version }}" \
            --notes "See the assets to download this version and install." \
            --draft=false \
            --prerelease=false
